# Generated by Django 4.0.4 on 2022-04-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('categorie', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Produit',
            },
        ),
    ]
