# Generated by Django 4.0.4 on 2022-04-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
